using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DivideGT
{
    public enum HeroEnum
    {
        NoData = 0,
        Unknown = 1,
        Swordsman = 2,
        Elesis = 3,
        Lire = 4,
        Arme = 5,
        Lass = 6,
        Ryan = 7,
        Ronan = 8,
        Amy = 9,
        Jin = 10,
        Sieghart = 11,
        Mari = 12,
        Dio = 13,
        Zero = 14,
        Ley = 15,
        Rufus = 16,
        Rin = 17,
        Asin = 18,
        Lime = 19,
        Edel = 20,
        Veigas = 21,
        Serdin = 22,
        Kanavan = 23, 
        Werner = 24,
        Grandiel = 25,
        Nelia = 26,
        Io = 27,
        Hwarin = 28,
        Europa = 29,
        Tia = 30,
        Lapis = 31,
        Harpe = 32,
        Callisto = 33,
        Cindy = 34,
        Ragnar = 35,
        Myst = 36,
        Ganymede = 37,
        Decanee = 38,
        Sol = 39,
        ElesisT = 40,
        ArmeT = 41,
        LireT = 42,
        RonanT = 43,
        MariT = 44,
        AmyT = 45,
        LimeT = 46,
        EdelT = 47,
        JinT = 48,
        LeyT = 49,
        HarpeT = 50,
        SerdinT = 51,
        SieghartT = 52,
        IoT = 53,
        LassT = 54,
        KanavanT = 55,
        Ai = 56,
        WernerT = 57,
        EuropaT = 58,
        LapisT = 59,
        HwarinT = 60,
        Mayden = 61,
        RagnarT = 62,
        RufusT = 63,
        Bastet = 64,
        ZeroT = 65,
        
    }
}
